### ISSUE TITLE
Dance Video Licensing

### ISSUE THREAD

**Issue by zgiles** [supertunaman/cdl#2]
Maybe some words should be added about the license of the dance video that is produced by the CDL. Concerns are mainly regarding dance videos that are licensed so that only <OWNER> can view it and not redistribute.  All rights should be given to the <OWNER> so that he/she can do whatever he/she wants with it.

**Comment by supertunaman** [comment]
Fixed in supertunaman/cdl@f0ae734f4abce311070ac0c401dbc0230cbc4344
